ktor:
  application:
    modules:
      - com.dw.ApplicationKt.module
  deployment:
    port: 8080
  jwt:
    secret: "secret"
    issuer: "issuer"
    audience: "**"
    realm: "access to the library"
    signatureAlgorithm: "HS256"
  psql-database:
    url: "jdbc:postgresql://localhost:5432/library"
    username: "postgres"
    password: "mysecretpassword"