package com.dw.plugins

import com.auth0.jwt.JWT
import com.auth0.jwt.algorithms.Algorithm
import com.dw.model.dto.Role
import com.dw.model.dto.UserDTO
import com.dw.service.authentication.JwtService
import io.ktor.client.request.*
import io.ktor.client.statement.*
import io.ktor.http.*
import io.ktor.server.auth.*
import io.ktor.server.config.*
import io.ktor.server.response.*
import io.ktor.server.routing.*
import io.ktor.server.testing.*
import java.util.*
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue
import kotlin.test.assertNotEquals

class JWTIntegrationTest {

    private val secret = "test-secret"
    private val issuer = "test-issuer"
    private val audience = "test-audience"
    private val realm = "test-realm"

    private val jwtConfigMap = mapOf(
        "ktor.jwt.secret" to secret,
        "ktor.jwt.issuer" to issuer,
        "ktor.jwt.audience" to audience,
        "ktor.jwt.realm" to realm
    )

    private fun testJWTApplication(block: suspend ApplicationTestBuilder.() -> Unit) = testApplication {
        environment {
            config = MapApplicationConfig(jwtConfigMap.toList())
        }
        application {
            configureJWT()
            routing {
                authenticate("auth-jwt") {
                    get("/protected") {
                        call.respondText("Success")
                    }
                }
            }
        }
        block()
    }

    @Test
    fun `protected route should be accessible with token generated by JwtService`() = testJWTApplication {
        val jwtService = JwtService(JwtConfig(secret, issuer, audience, realm))
        val tokenPair = jwtService.generateToken(UserDTO(1, "Test User", "test@example.com", "password", Role.USER))

        val response = client.get("/protected") {
            header(HttpHeaders.Authorization, "Bearer ${tokenPair.first}")
        }

        assertEquals(HttpStatusCode.OK, response.status)
        assertEquals("Success", response.bodyAsText())
    }

    @Test
    fun `protected route should succeed with a valid access_token cookie and set no new cookie`() = testJWTApplication {
        val jwtService = JwtService(JwtConfig(secret, issuer, audience, realm))
        val tokenPair = jwtService.generateToken(UserDTO(1, "Test User", "test@example.com", "password", Role.USER))

        val response = client.get("/protected") {
            cookie("access_token", tokenPair.first)
        }

        assertEquals(HttpStatusCode.OK, response.status)
        assertEquals("Success", response.bodyAsText())
        assertTrue(response.headers.getAll(HttpHeaders.SetCookie).isNullOrEmpty())
    }

    @Test
    fun `protected route should transparently refresh an expired access_token using a valid refresh_token cookie`() = testJWTApplication {
        val jwtService = JwtService(JwtConfig(secret, issuer, audience, realm))
        val tokenPair = jwtService.generateToken(UserDTO(1, "Test User", "test@example.com", "password", Role.USER))
        val expiredAccessToken = JWT.create()
            .withAudience(audience)
            .withIssuer(issuer)
            .withClaim("email", "test@example.com")
            .withClaim("role", "USER")
            .withClaim("userId", 1L)
            .withClaim("type", "access")
            .withExpiresAt(Date(System.currentTimeMillis() - 1000))
            .sign(Algorithm.HMAC256(secret))

        val response = client.get("/protected") {
            cookie("access_token", expiredAccessToken)
            cookie("refresh_token", tokenPair.second)
        }

        assertEquals(HttpStatusCode.OK, response.status)
        assertEquals("Success", response.bodyAsText())

        val setCookies = response.headers.getAll(HttpHeaders.SetCookie).orEmpty().map { parseServerSetCookieHeader(it) }
        val newAccessCookie = setCookies.first { it.name == "access_token" }
        assertTrue(newAccessCookie.value.isNotEmpty())
        assertNotEquals(expiredAccessToken, newAccessCookie.value)
        assertTrue(newAccessCookie.httpOnly)
        assertEquals("None", newAccessCookie.extensions["SameSite"])
    }

    @Test
    fun `protected route should return 401 when both access_token and refresh_token are expired`() = testJWTApplication {
        fun expiredToken(type: String) = JWT.create()
            .withAudience(audience)
            .withIssuer(issuer)
            .withClaim("email", "test@example.com")
            .withClaim("role", "USER")
            .withClaim("userId", 1L)
            .withClaim("type", type)
            .withExpiresAt(Date(System.currentTimeMillis() - 1000))
            .sign(Algorithm.HMAC256(secret))

        val response = client.get("/protected") {
            cookie("access_token", expiredToken("access"))
            cookie("refresh_token", expiredToken("refresh"))
        }

        assertEquals(HttpStatusCode.Unauthorized, response.status)
    }

    @Test
    fun `protected route should return 401 when the refresh_token cookie actually holds an access token`() = testJWTApplication {
        val jwtService = JwtService(JwtConfig(secret, issuer, audience, realm))
        val tokenPair = jwtService.generateToken(UserDTO(1, "Test User", "test@example.com", "password", Role.USER))
        val expiredAccessToken = JWT.create()
            .withAudience(audience)
            .withIssuer(issuer)
            .withClaim("email", "test@example.com")
            .withClaim("type", "access")
            .withExpiresAt(Date(System.currentTimeMillis() - 1000))
            .sign(Algorithm.HMAC256(secret))

        val response = client.get("/protected") {
            cookie("access_token", expiredAccessToken)
            cookie("refresh_token", tokenPair.first)
        }

        assertEquals(HttpStatusCode.Unauthorized, response.status)
    }

    @Test
    fun `protected route should return 401 for a refresh-type token presented as a bearer token`() = testJWTApplication {
        val token = JWT.create()
            .withAudience(audience)
            .withIssuer(issuer)
            .withClaim("email", "testuser@example.com")
            .withClaim("type", "refresh")
            .withExpiresAt(Date(System.currentTimeMillis() + 3600000))
            .sign(Algorithm.HMAC256(secret))

        val response = client.get("/protected") {
            header(HttpHeaders.Authorization, "Bearer $token")
        }

        assertEquals(HttpStatusCode.Unauthorized, response.status)
    }

    @Test
    fun `protected route should return 401 for a bearer token with no type claim`() = testJWTApplication {
        val token = JWT.create()
            .withAudience(audience)
            .withIssuer(issuer)
            .withClaim("email", "testuser@example.com")
            .withExpiresAt(Date(System.currentTimeMillis() + 3600000))
            .sign(Algorithm.HMAC256(secret))

        val response = client.get("/protected") {
            header(HttpHeaders.Authorization, "Bearer $token")
        }

        assertEquals(HttpStatusCode.Unauthorized, response.status)
    }

    @Test
    fun `protected route should be accessible with token containing email claim`() = testJWTApplication {
        val token = JWT.create()
            .withAudience(audience)
            .withIssuer(issuer)
            .withClaim("email", "testuser@example.com")
            .withClaim("type", "access")
            .withExpiresAt(Date(System.currentTimeMillis() + 3600000))
            .sign(Algorithm.HMAC256(secret))

        val response = client.get("/protected") {
            header(HttpHeaders.Authorization, "Bearer $token")
        }

        assertEquals(HttpStatusCode.OK, response.status)
        assertEquals("Success", response.bodyAsText())
    }

    @Test
    fun `protected route should return 401 for expired token`() = testJWTApplication {
        val token = JWT.create()
            .withAudience(audience)
            .withIssuer(issuer)
            .withClaim("email", "testuser@example.com")
            .withExpiresAt(Date(System.currentTimeMillis() - 1000)) // Expired 1 second ago
            .sign(Algorithm.HMAC256(secret))

        val response = client.get("/protected") {
            header(HttpHeaders.Authorization, "Bearer $token")
        }

        assertEquals(HttpStatusCode.Unauthorized, response.status)
    }

    @Test
    fun `protected route should return 401 for token with invalid secret`() = testJWTApplication {
        val token = JWT.create()
            .withAudience(audience)
            .withIssuer(issuer)
            .withClaim("email", "testuser@example.com")
            .withExpiresAt(Date(System.currentTimeMillis() + 3600000))
            .sign(Algorithm.HMAC256("wrong-secret"))

        val response = client.get("/protected") {
            header(HttpHeaders.Authorization, "Bearer $token")
        }

        assertEquals(HttpStatusCode.Unauthorized, response.status)
    }

    @Test
    fun `protected route should return 401 for token with invalid issuer`() = testJWTApplication {
        val token = JWT.create()
            .withAudience(audience)
            .withIssuer("other-issuer")
            .withClaim("email", "testuser@example.com")
            .withExpiresAt(Date(System.currentTimeMillis() + 3600000))
            .sign(Algorithm.HMAC256(secret))

        val response = client.get("/protected") {
            header(HttpHeaders.Authorization, "Bearer $token")
        }

        assertEquals(HttpStatusCode.Unauthorized, response.status)
    }

    @Test
    fun `protected route should return 401 for token with invalid audience`() = testJWTApplication {
        val token = JWT.create()
            .withAudience("other-audience")
            .withIssuer(issuer)
            .withClaim("email", "testuser@example.com")
            .withExpiresAt(Date(System.currentTimeMillis() + 3600000))
            .sign(Algorithm.HMAC256(secret))

        val response = client.get("/protected") {
            header(HttpHeaders.Authorization, "Bearer $token")
        }

        assertEquals(HttpStatusCode.Unauthorized, response.status)
    }

    @Test
    fun `protected route should return 401 for token with missing claim`() = testJWTApplication {
        val token = JWT.create()
            .withAudience(audience)
            .withIssuer(issuer)
            // missing email claim
            .withExpiresAt(Date(System.currentTimeMillis() + 3600000))
            .sign(Algorithm.HMAC256(secret))

        val response = client.get("/protected") {
            header(HttpHeaders.Authorization, "Bearer $token")
        }

        assertEquals(HttpStatusCode.Unauthorized, response.status)
    }
}
