package com.dw.plugins

import com.auth0.jwt.JWT
import com.auth0.jwt.algorithms.Algorithm
import com.dw.model.dto.Role
import com.dw.model.dto.UserDTO
import com.dw.service.authentication.JwtService
import io.ktor.client.request.*
import io.ktor.client.statement.*
import io.ktor.http.*
import io.ktor.server.auth.*
import io.ktor.server.config.*
import io.ktor.server.response.*
import io.ktor.server.routing.*
import io.ktor.server.testing.*
import java.util.*
import kotlin.test.Test
import kotlin.test.assertEquals

class JWTIntegrationTest {

    private val secret = "test-secret"
    private val issuer = "test-issuer"
    private val audience = "test-audience"
    private val realm = "test-realm"

    private val jwtConfigMap = mapOf(
        "ktor.jwt.secret" to secret,
        "ktor.jwt.issuer" to issuer,
        "ktor.jwt.audience" to audience,
        "ktor.jwt.realm" to realm
    )

    private fun testJWTApplication(block: suspend ApplicationTestBuilder.() -> Unit) = testApplication {
        environment {
            config = MapApplicationConfig(jwtConfigMap.toList())
        }
        application {
            configureJWT()
            routing {
                authenticate("auth-jwt") {
                    get("/protected") {
                        call.respondText("Success")
                    }
                }
            }
        }
        block()
    }

    @Test
    fun `protected route should be accessible with token generated by JwtService`() = testJWTApplication {
        val jwtService = JwtService(JwtConfig(secret, issuer, audience, realm))
        val token = jwtService.generateToken(UserDTO(1, "Test User", "test@example.com", "password", Role.USER))

        val response = client.get("/protected") {
            header(HttpHeaders.Authorization, "Bearer $token")
        }

        assertEquals(HttpStatusCode.OK, response.status)
        assertEquals("Success", response.bodyAsText())
    }

    @Test
    fun `protected route should be accessible with token containing email claim`() = testJWTApplication {
        val token = JWT.create()
            .withAudience(audience)
            .withIssuer(issuer)
            .withClaim("email", "testuser@example.com")
            .withExpiresAt(Date(System.currentTimeMillis() + 3600000))
            .sign(Algorithm.HMAC256(secret))

        val response = client.get("/protected") {
            header(HttpHeaders.Authorization, "Bearer $token")
        }

        assertEquals(HttpStatusCode.OK, response.status)
        assertEquals("Success", response.bodyAsText())
    }

    @Test
    fun `protected route should return 401 for expired token`() = testJWTApplication {
        val token = JWT.create()
            .withAudience(audience)
            .withIssuer(issuer)
            .withClaim("email", "testuser@example.com")
            .withExpiresAt(Date(System.currentTimeMillis() - 1000)) // Expired 1 second ago
            .sign(Algorithm.HMAC256(secret))

        val response = client.get("/protected") {
            header(HttpHeaders.Authorization, "Bearer $token")
        }

        assertEquals(HttpStatusCode.Unauthorized, response.status)
    }

    @Test
    fun `protected route should return 401 for token with invalid secret`() = testJWTApplication {
        val token = JWT.create()
            .withAudience(audience)
            .withIssuer(issuer)
            .withClaim("email", "testuser@example.com")
            .withExpiresAt(Date(System.currentTimeMillis() + 3600000))
            .sign(Algorithm.HMAC256("wrong-secret"))

        val response = client.get("/protected") {
            header(HttpHeaders.Authorization, "Bearer $token")
        }

        assertEquals(HttpStatusCode.Unauthorized, response.status)
    }

    @Test
    fun `protected route should return 401 for token with missing claim`() = testJWTApplication {
        val token = JWT.create()
            .withAudience(audience)
            .withIssuer(issuer)
            // missing email claim
            .withExpiresAt(Date(System.currentTimeMillis() + 3600000))
            .sign(Algorithm.HMAC256(secret))

        val response = client.get("/protected") {
            header(HttpHeaders.Authorization, "Bearer $token")
        }

        assertEquals(HttpStatusCode.Unauthorized, response.status)
    }
}
