ALTER TABLE "user" ADD COLUMN IF NOT EXISTS "created_on" VARCHAR(255);
ALTER TABLE "user" ADD COLUMN IF NOT EXISTS "created_by" BIGINT;
ALTER TABLE "user" ADD COLUMN IF NOT EXISTS "modified_on" VARCHAR(255);
ALTER TABLE "user" ADD COLUMN IF NOT EXISTS "modified_by" BIGINT;

ALTER TABLE "author" ADD COLUMN IF NOT EXISTS "user_id" BIGINT;
ALTER TABLE "author" ADD COLUMN IF NOT EXISTS "created_on" VARCHAR(255);
ALTER TABLE "author" ADD COLUMN IF NOT EXISTS "created_by" BIGINT;
ALTER TABLE "author" ADD COLUMN IF NOT EXISTS "modified_on" VARCHAR(255);
ALTER TABLE "author" ADD COLUMN IF NOT EXISTS "modified_by" BIGINT;

ALTER TABLE "book" ADD COLUMN IF NOT EXISTS "translator" VARCHAR(255);
ALTER TABLE "book" ADD COLUMN IF NOT EXISTS "image" VARCHAR(255);
ALTER TABLE "book" ADD COLUMN IF NOT EXISTS "user_id" BIGINT;
ALTER TABLE "book" ADD COLUMN IF NOT EXISTS "created_on" VARCHAR(255);
ALTER TABLE "book" ADD COLUMN IF NOT EXISTS "created_by" BIGINT;
ALTER TABLE "book" ADD COLUMN IF NOT EXISTS "modified_on" VARCHAR(255);
ALTER TABLE "book" ADD COLUMN IF NOT EXISTS "modified_by" BIGINT;
